[pytest]
minversion = 7.0
addopts = -ra -q
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning
# Discover tests inside these module directories
testpaths =
    infrastructure/tests
    storage/tests
    cli/tests
    api/tests
    metadata/tests
    query/tests
